add_parcel:
  name: Add parcel
  description: Add a new parcel tracking number.
  fields:
    tracking_number:
      required: true
      selector:
        text:
    name:
      required: false
      selector:
        text:
